# Generated by Django 2.1.7 on 2021-10-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211018_1213'),
        ('users', '0003_auto_20211004_0609'),
    ]

    operations = [
    ]
