# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-10-16 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20211016_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='default_image',
        ),
        migrations.AddField(
            model_name='sku',
            name='default_imag',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='默认图片'),
        ),
    ]
