# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-10-16 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20211016_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='default_imag',
            new_name='default_image',
        ),
    ]
